version: "3"

services:
  kamailio:
    image: opensips:test
    build:
      context: .
      dockerfile: Dockerfile.opensips
    volumes:
      - ./opensips:/etc/opensips
    ports:
      - "5060"
    networks:
      main:
        aliases:
          - kamailio
    depends_on:
      - db
  
  asterisk:
    image: asterisk:test
    build:
      context: .
      dockerfile: Dockerfile.asterisk
    networks:
      main:
        aliases:
          - asterisk
    volumes:
      - ./asterisk:/etc/asterisk

  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: 'opensips'
      MYSQL_USER: 'opensips'
      MYSQL_PASSWORD: 'opensips'
      MYSQL_ROOT_PASSWORD: 'dbrootpw'
    networks:
      main:
        aliases:
          - db
networks:
  main: